import Link from "next/link";
import { MoveLeft, AlertTriangle } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950 text-black dark:text-white font-mono p-10">
      <Link href="/" className="flex items-center gap-2 text-sm mb-12 opacity-50 hover:opacity-100 transition-opacity">
        <MoveLeft className="h-4 w-4" /> Return to Root
      </Link>

      <article className="max-w-2xl mx-auto space-y-10">
        <header className="space-y-4">
          <h1 className="text-4xl tracking-tighter text-orange-500">USER_AGREEMENT</h1>
          <p className="text-xs text-zinc-400">LAST_REVISED: APRIL_2026</p>
        </header>

        {/* CRITICAL MEDICAL DISCLAIMER BOX */}
        <section className="border-2 border-red-500/20 bg-red-500/5 p-6 rounded-2xl space-y-3">
          <div className="flex items-center gap-2 text-red-500">
            <AlertTriangle className="h-5 w-5" />
            <h2 className="text-sm font-bold uppercase tracking-widest">Medical Disclaimer</h2>
          </div>
          <p className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed">
            HolisticAI is a technical demonstration for wellness optimization. It is <span className="text-red-500 font-bold underline">not a medical application</span>. The AI-generated content does not constitute medical advice, diagnosis, or treatment. 
          </p>
          <p className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed font-bold">
            If you have a serious health concern or are experiencing a medical emergency, you must seek immediate attention from a licensed medical professional. Do not delay seeking professional advice because of something generated by this script.
          </p>
        </section>

        <div className="space-y-8 text-sm text-zinc-500 leading-relaxed">
          <section className="space-y-4">
            <h3 className="text-white text-xs uppercase tracking-widest">01. System Purpose</h3>
            <p>
              This software is a project designed to demonstrate full-stack engineering proficiency to solve a problem and assist developer or programmers. It is intended for the open source community evaluation and educational use only.
            </p>
          </section>

          <section className="space-y-4">
            <h3 className="text-white text-xs uppercase tracking-widest">02. Usage Protocols</h3>
            <ul className="space-y-4">
              <li className="flex gap-4">
                <span className="text-orange-500 font-bold">[-]</span>
                <span>Users shall not input sensitive personal, financial, or private health identifiers into the system.</span>
              </li>
              <li className="flex gap-4">
                <span className="text-orange-500 font-bold">[-]</span>
                <span>The system is provided "as-is" without warranties of any kind regarding the accuracy of AI-generated wellness scripts.</span>
              </li>
              <li className="flex gap-4">
                <span className="text-orange-500 font-bold">[-]</span>
                <span>Any attempt to reverse-engineer or "jailbreak" the underlying LLM logic is prohibited.</span>
              </li>
            </ul>
          </section>
        </div>

        <footer className="pt-10 opacity-30 hover:opacity-100 transition-opacity">
          <Link href="/" className="text-xs border-b border-black dark:border-white pb-1">
            Terminate Session & Exit
          </Link>
        </footer>
      </article>
    </div>
  );
}